spring:
  data:
    mongodb:
      host: ordering.mongo
      port: 27017
      database: ordering
  redis:
    host: ordering.redis
    port: 6379

logging:
  file:
    name: ordering.log
  level:
    root: info

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30