spring:
  data:
    mongodb:
      host: ordering.mongo
      port: 27017
      database: ordering
  redis:
    host: ordering.redis
    port: 6379

logging:
  file:
    name: /usr/local/tomcat/logs/ordering/ordering.log
  level:
    root: info

token:
  jwt:
    header: Authorization
    secret: thisdkOrderingSecretKey
    expiration: 604800000