spring:
  data:
    mongodb:
      host: 121.4.84.105
      port: 27017
      database: ordering
  redis:
    host: 121.4.84.105
    port: 6379

logging:
  file:
    name: /usr/local/tomcat/logs/ordering.log
  level:
    root: info

token:
  cms:
    jwtSecret: orderingSecretKey
    jwtExpirationMs: 86400000