name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootWar
      - name: Copy war to Root
        run: mv build/libs/*.war ./ordering.war
      - name: Upload to Coding
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
          git config --global user.name thisdk
          git config --global user.email thisdk@gmail.com
          git clone git@e.coding.net:thisdk/ordering-service/ordering-deploy.git
          cp ordering.war ordering-deploy/ -f
          cd ordering-deploy
          git add * && git commit -a -m "Deploy"
          git push -u origin master
      - name: Upload to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ordering
          path: ordering.war
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/war
            ./deploy.sh
            
